23TH2508_Final_Project/23TH2508_Final_Project/Controllers/HoaDons_23TH2508Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _23TH2508_Final_Project.Models;

namespace _23TH2508_Final_Project.Controllers
{
    public class HoaDons_23TH2508Controller : Controller
    {
        private QuanLyQuanCafeEntities db = new QuanLyQuanCafeEntities();

        // GET: HoaDons_23TH2508
        public ActionResult Index(string searchTerm, int page = 1)
        {
            int pageSize = 10; // Số lượng hóa đơn trên mỗi trang
            var hoaDons = db.HoaDons.Include(h => h.KhachHang).Include(h => h.NhanVien);

            if (!String.IsNullOrEmpty(searchTerm))
            {
                hoaDons = hoaDons.Where(h => h.HoaDonID.Contains(searchTerm));
            }

            var pagedHoaDons = hoaDons.OrderBy(h => h.HoaDonID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            int totalRecords = hoaDons.Count();
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalRecords / pageSize);
            ViewBag.CurrentPage = page;

            return View(pagedHoaDons);
        }

        // GET: HoaDons_23TH2508/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Sử dụng Include để tải dữ liệu liên quan từ bảng ChiTietHoaDon
            HoaDon hoaDon = db.HoaDons
                .Include(h => h.ChiTietHoaDons.Select(ct => ct.SanPham))
                .Include(h => h.KhachHang)
                .Include(h => h.NhanVien)
                .FirstOrDefault(h => h.HoaDonID == id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // GET: HoaDons_23TH2508/Create
        public ActionResult Create()
        {
            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "HoTen");
            ViewBag.NhanVienID = new SelectList(db.NhanViens, "NhanVienID", "HoTen");
            return View();
        }

        // POST: HoaDons_23TH2508/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HoaDonID,NgayLap,ThoiGianLap,NhanVienID,KhachHangID,TongTien")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                DateTime ngayLap;
                if (DateTime.TryParseExact(Request.Form["NgayLap"], "MM/dd/yyyy", null, System.Globalization.DateTimeStyles.None, out ngayLap))
                {
                    hoaDon.NgayLap = ngayLap;

                    // Chuyển đổi giá trị ThoiGianLap thành TimeSpan
                    TimeSpan thoiGianLap;
                    if (TimeSpan.TryParse(Request.Form["ThoiGianLap"], out thoiGianLap))
                    {
                        hoaDon.ThoiGianLap = thoiGianLap;
                    }
                    else
                    {
                        ModelState.AddModelError("ThoiGianLap", "Thời gian lập không hợp lệ.");
                    }

                    // Chuyển đổi giá trị TongTien thành số nguyên
                    hoaDon.TongTien = decimal.Parse(Request.Form["TongTienInput"].Replace(".", ""));

                    db.HoaDons.Add(hoaDon);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException ex)
                    {
                        foreach (var validationErrors in ex.EntityValidationErrors)
                        {
                            foreach (var validationError in validationErrors.ValidationErrors)
                            {
                                ModelState.AddModelError(validationError.PropertyName, validationError.ErrorMessage);
                            }
                        }
                        ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "HoTen", hoaDon.KhachHangID);
                        ViewBag.NhanVienID = new SelectList(db.NhanViens, "NhanVienID", "HoTen", hoaDon.NhanVienID);
                        return View(hoaDon);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("NgayLap", "Ngày lập không hợp lệ.");
                }
            }

            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "HoTen", hoaDon.KhachHangID);
            ViewBag.NhanVienID = new SelectList(db.NhanViens, "NhanVienID", "HoTen", hoaDon.NhanVienID);
            return View(hoaDon);
        }

        // GET: HoaDons_23TH2508/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "HoTen", hoaDon.KhachHangID);
            ViewBag.NhanVienID = new SelectList(db.NhanViens, "NhanVienID", "HoTen", hoaDon.NhanVienID);
            return View(hoaDon);
        }

        // POST: HoaDons_23TH2508/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HoaDonID,NgayLap,NhanVienID,KhachHangID,TongTien")] HoaDon hoaDon, string TongTienInput)
        {
            if (ModelState.IsValid)
            {
                // Chuyển đổi giá trị TongTien từ chuỗi có dấu phẩy thành số nguyên
                hoaDon.TongTien = decimal.Parse(TongTienInput.Replace(".", ""));

                DateTime ngayLap;
                if (DateTime.TryParseExact(Request.Form["NgayLap"], "MM/dd/yyyy", null, System.Globalization.DateTimeStyles.None, out ngayLap))
                {
                    hoaDon.NgayLap = ngayLap;

                    // Chuyển đổi giá trị ThoiGianLap thành TimeSpan
                    TimeSpan thoiGianLap;
                    if (TimeSpan.TryParse(Request.Form["ThoiGianLap"], out thoiGianLap))
                    {
                        hoaDon.ThoiGianLap = thoiGianLap;
                    }
                    else
                    {
                        ModelState.AddModelError("ThoiGianLap", "Thời gian lập không hợp lệ.");
                    }

                    // Chuyển đổi giá trị TongTien thành số nguyên
                    hoaDon.TongTien = decimal.Parse(Request.Form["TongTienInput"].Replace(".", ""));

                    db.Entry(hoaDon).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("NgayLap", "Ngày lập không hợp lệ.");
                }
            }

            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "HoTen", hoaDon.KhachHangID);
            ViewBag.NhanVienID = new SelectList(db.NhanViens, "NhanVienID", "HoTen", hoaDon.NhanVienID);
            return View(hoaDon);
        }

        // GET: HoaDons_23TH2508/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // POST: HoaDons_23TH2508/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HoaDon hoaDon = db.HoaDons.Find(id);
            db.HoaDons.Remove(hoaDon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        private string GenerateNewHoaDonID()
        {
            var maxID = db.HoaDons
                .Select(h => h.HoaDonID)
                .ToList()// Load IDs into memory
                .Where(id => id.StartsWith("HD"))
                .Select(id => int.Parse(id.Substring(2)))
                .DefaultIfEmpty(0)
                .Max(); return "HD" + (maxID + 1)
                .ToString("D4");
        }

        // GET: HoaDons/TimKiem_HD
        public ActionResult TimKiem_HD()
        {
            var hoaDons = db.HoaDons.Include(h => h.KhachHang).Include(h => h.NhanVien).ToList();
            return View(hoaDons);
        }


        // GET: HoaDons/TimKiem_HD_KQ
        public ActionResult TimKiem_HD_KQ(string searchID, DateTime? searchDateFrom, DateTime? searchDateTo, TimeSpan? searchTimeFrom, TimeSpan? searchTimeTo, decimal? searchAmountFrom, decimal? searchAmountTo)
        {
            var hoaDons = db.Database.SqlQuery<HoaDon>("EXEC HoaDon_TimKiem @HoaDonID, @NgayLapFrom, @NgayLapTo, @ThoiGianLapFrom, @ThoiGianLapTo, @TongTienFrom, @TongTienTo",
                new SqlParameter("@HoaDonID", (object)searchID ?? DBNull.Value),

23TH2508_Final_Project/23TH2508_Final_Project/Controllers/SanPhams_23TH2508Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _23TH2508_Final_Project.Models;

namespace _23TH2508_Final_Project.Controllers
{
    public class SanPhams_23TH2508Controller : Controller
    {
        private QuanLyQuanCafeEntities db = new QuanLyQuanCafeEntities();

        // GET: SanPhams_23TH2508
        public ActionResult Index(int page = 1)
        {
            int pageSize = 8; // Số lượng sản phẩm trên mỗi trang
            var sanPhams = db.SanPhams.OrderBy(s => s.SanPhamID);

            var pagedSanPhams = sanPhams.Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            int totalRecords = sanPhams.Count();
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalRecords / pageSize);
            ViewBag.CurrentPage = page;

            return View(pagedSanPhams);
        }

        // GET: SanPhams_23TH2508/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams_23TH2508/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SanPhams_23TH2508/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SanPhamID,TenSanPham,Gia,MoTa,HinhAnh")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sanPham);
        }

        // GET: SanPhams_23TH2508/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams_23TH2508/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SanPhamID,TenSanPham,Gia,MoTa,HinhAnh")] SanPham sanPham, HttpPostedFileBase HinhAnh, string GiaInput)
        {
            if (ModelState.IsValid)
            {
                // Chuyển đổi giá trị Gia từ chuỗi có dấu phẩy thành số nguyên
                sanPham.Gia = decimal.Parse(GiaInput.Replace(".", ""));

                // Kiểm tra xem người dùng có chọn ảnh mới không
                if (HinhAnh != null && HinhAnh.ContentLength > 0)
                {
                    // Lưu ảnh vào thư mục /Images/products/
                    var fileName = Path.GetFileName(HinhAnh.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/products/"), fileName);
                    HinhAnh.SaveAs(path);

                    // Cập nhật đường dẫn ảnh trong model
                    sanPham.HinhAnh = fileName;
                }

                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sanPham);
        }

        // GET: SanPhams_23TH2508/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams_23TH2508/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

23TH2508_Final_Project/23TH2508_Final_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Management Cafe</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
        <div class="container-fluid">
            @Html.ActionLink("Management Cafe", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav" style="gap: 1rem;">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    @if (Session["AdminEmail"] != null)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHoaDons" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Hóa Đơn
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownHoaDons">
                                <li>@Html.ActionLink("Trang chính", "Index", "HoaDons_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Create", "Create", "HoaDons_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Chi Tiết Hóa Đơn", "Index", "ChiTietHoaDons_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownKhachHangs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Khách hàng
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownKhachHangs">
                                <li>@Html.ActionLink("Trang chính", "Index", "KhachHangs_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Tạo mới", "Create", "KhachHangs_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownNhanViens" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Nhân Viên
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownNhanViens">
                                <li>@Html.ActionLink("Trang chính", "Index", "NhanViens_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Tạo mới", "Create", "NhanViens_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownSanPhams" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Sản Phẩm
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownSanPhams">
                                <li>@Html.ActionLink("Trang chính", "Index", "SanPhams_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Tạo mới", "Create", "SanPhams_23TH2508", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Nhóm 6 &copy; @DateTime.Now.Year - Management Cafe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>